import type { Metadata } from 'next';
export const metadata: Metadata = {
  title: 'Shopify Sitemap: Location, Errors, and How to Submit It | SitemapFixer',
  description: "Shopify automatically generates your sitemap.xml. Here is where to find it, what it includes, common errors, and how to submit it to Google Search Console.",
  alternates: { canonical: 'https://sitemapfixer.com/learn/shopify-sitemap' },
};
export default function Page() {
  return (
    <div style={{ maxWidth: 800, margin: '0 auto', padding: '60px 24px' }}>
      <nav style={{ fontSize: 13, color: '#6b6b7d', marginBottom: 32 }}>
        <a href="/" style={{ color: '#2d5be3', textDecoration: 'none' }}>Home</a>{' / '}
        <a href="/learn" style={{ color: '#2d5be3', textDecoration: 'none' }}>Learn</a>{' / '}
        <span>Shopify Sitemap</span>
      </nav>
      <h1 style={{ fontSize: 40, fontWeight: 700, color: '#0a0a0f', marginBottom: 16, lineHeight: 1.15 }}>Shopify Sitemap: Where It Is and How to Use It</h1>
      <div style={{ background: '#eef1ff', border: '1px solid rgba(45,91,227,0.2)', borderRadius: 12, padding: '16px 20px', marginBottom: 40, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16 }}>
        <span style={{ fontSize: 14, color: '#2d5be3', fontWeight: 500 }}>Validate your Shopify sitemap free</span>
        <a href="/" style={{ background: '#2d5be3', color: 'white', padding: '10px 20px', borderRadius: 8, textDecoration: 'none', fontWeight: 600, fontSize: 13 }}>Check My Sitemap</a>
      </div>
      <div style={{ fontSize: 16, color: '#3d3d4f', lineHeight: 1.85 }}>
        <p style={{ marginBottom: 24 }}>Shopify automatically generates and maintains your sitemap - you do not need to install a plugin or configure anything. Your sitemap is always at yourstore.com/sitemap.xml. It updates automatically whenever you add or remove products, pages, blog posts, or collections.</p>

        <h2 style={{ fontSize: 26, fontWeight: 700, color: '#0a0a0f', marginTop: 48, marginBottom: 16 }}>What Your Shopify Sitemap Includes</h2>
        <p style={{ marginBottom: 24 }}>The Shopify sitemap.xml is a sitemap index that links to several child sitemaps: sitemap_products_1.xml (all product pages), sitemap_pages_1.xml (standalone pages like About and Contact), sitemap_collections_1.xml (collection/category pages), and sitemap_blogs_1.xml (blog posts if you have a blog). Each child sitemap can hold up to 5,000 URLs. If you have more, Shopify creates sitemap_products_2.xml and so on.</p>

        <h2 style={{ fontSize: 26, fontWeight: 700, color: '#0a0a0f', marginTop: 48, marginBottom: 16 }}>What Shopify Does NOT Include in the Sitemap</h2>
        <p style={{ marginBottom: 24 }}>Pages that are password-protected are excluded. Variants of products are not included - only the main product URL is in the sitemap. Policy pages (refund policy, shipping policy, privacy policy, terms of service) generated by Shopify are excluded because they are canonical to Shopify itself. Search results pages, cart pages, and account pages are also excluded - this is correct behavior since these should not be indexed.</p>

        <h2 style={{ fontSize: 26, fontWeight: 700, color: '#0a0a0f', marginTop: 48, marginBottom: 16 }}>How to Submit Your Shopify Sitemap to Google</h2>
        <p style={{ marginBottom: 24 }}>Go to Google Search Console and select your Shopify store property. Click Sitemaps in the left menu. Enter sitemap.xml and click Submit. You do not need to submit each child sitemap separately - submitting the index file is enough. Google will discover and process all the child sitemaps automatically.</p>

        <h2 style={{ fontSize: 26, fontWeight: 700, color: '#0a0a0f', marginTop: 48, marginBottom: 16 }}>Common Shopify Sitemap Problems</h2>

        <h3 style={{ fontSize: 20, fontWeight: 700, color: '#0a0a0f', marginTop: 32, marginBottom: 10 }}>Password-protected store blocks Google</h3>
        <p style={{ marginBottom: 24 }}>If your store is password-protected (common during development), your entire sitemap returns a 401 or redirects to the password page. Google cannot index any pages. Make sure to disable the password protection before going live. Go to Online Store, then Preferences, and remove the password.</p>

        <h3 style={{ fontSize: 20, fontWeight: 700, color: '#0a0a0f', marginTop: 32, marginBottom: 10 }}>Duplicate product URLs</h3>
        <p style={{ marginBottom: 24 }}>Shopify products can be accessed via two URL patterns: /products/product-name and /collections/collection-name/products/product-name. Both return the same content. Shopify handles this with canonical tags pointing to /products/product-name, but the collection-path URLs still exist. Only the canonical URL appears in the sitemap, which is correct - but verify this is working by checking the canonical tags in your product page source.</p>

        <h3 style={{ fontSize: 20, fontWeight: 700, color: '#0a0a0f', marginTop: 32, marginBottom: 10 }}>Out-of-stock products still indexed</h3>
        <p style={{ marginBottom: 24 }}>By default, even out-of-stock products remain in your sitemap and are indexed. Whether you want them indexed depends on your strategy. If the product will return to stock, keep it indexed with updated schema markup showing availability. If it is permanently removed, either delete the product or create a redirect to a similar product before deletion - never just delete without redirecting.</p>

        <h3 style={{ fontSize: 20, fontWeight: 700, color: '#0a0a0f', marginTop: 32, marginBottom: 10 }}>Missing collection pages</h3>
        <p style={{ marginBottom: 24 }}>All active collections appear in the sitemap by default. If you notice collections missing, check that they are set to Active (not Hidden) and that they have at least one product. Empty or hidden collections do not appear in the sitemap.</p>

        <h2 style={{ fontSize: 26, fontWeight: 700, color: '#0a0a0f', marginTop: 48, marginBottom: 16 }}>Can You Customize the Shopify Sitemap?</h2>
        <p style={{ marginBottom: 24 }}>Shopify does not provide a built-in way to exclude specific pages or products from the sitemap. However, you can exclude pages from indexing using the noindex meta tag - Shopify will still include them in the sitemap, but Google will not index them (though this creates a contradiction you should fix eventually). For advanced sitemap customization, third-party Shopify apps like SEO Manager or Sitemap Noindex give you more control.</p>
      </div>
      <div style={{ background: '#0a0a0f', borderRadius: 12, padding: '32px', textAlign: 'center', marginTop: 56 }}>
        <div style={{ fontSize: 20, fontWeight: 700, color: 'white', marginBottom: 8 }}>Check your Shopify sitemap for issues</div>
        <div style={{ color: '#9999aa', marginBottom: 20, fontSize: 14 }}>Free - checks every URL in 60 seconds</div>
        <a href="/" style={{ background: 'white', color: '#0a0a0f', padding: '14px 28px', borderRadius: 8, textDecoration: 'none', fontWeight: 700 }}>Analyze My Sitemap Free</a>
      </div>
    </div>
  );
}
