'use client';
import { useState } from 'react';
import { Hero } from '@/components/Hero';
import { Loading } from '@/components/Loading';
import { Results } from '@/components/Results';
import { PaywallModal } from '@/components/PaywallModal';

type AppState = 'idle' | 'loading' | 'results' | 'error';

function Logo() { return (<a href="/" style={{ display:'flex',alignItems:'center',gap:8,textDecoration:'none' }}><svg width="28" height="28" viewBox="0 0 28 28" fill="none"><rect width="28" height="28" rx="7" fill="#0a0a0f"/><path d="M7 9h14M7 14h10M7 19h12" stroke="white" strokeWidth="2" strokeLinecap="round"/><circle cx="21" cy="19" r="3" fill="#2d5be3"/></svg><span style={{ fontFamily:"'Instrument Serif',serif",fontSize:20,color:'var(--ink)' }}>SitemapFixer</span></a>); }

function Navbar() { return (<nav style={{ borderBottom:'1px solid var(--border)',background:'rgba(250,250,249,0.85)',backdropFilter:'blur(12px)',position:'sticky',top:0,zIndex:100 }}><div style={{ maxWidth:960,margin:'0 auto',padding:'14px 24px',display:'flex',alignItems:'center',justifyContent:'space-between' }}><Logo /><div style={{ display:'flex',gap:24,alignItems:'center' }}><a href="/learn" style={{ fontSize:14,color:'var(--muted)',textDecoration:'none' }}>Learn</a><a href="/blog" style={{ fontSize:14,color:'var(--muted)',textDecoration:'none' }}>Blog</a><a href="/pricing" style={{ fontSize:13,color:'white',background:'#2d5be3',padding:'6px 14px',borderRadius:8,textDecoration:'none',fontWeight:600 }}>Pricing</a></div></div></nav>); }

function Footer() { return (<footer style={{ borderTop:'1px solid var(--border)',background:'var(--paper)',padding:'56px 24px 40px' }}><div style={{ maxWidth:960,margin:'0 auto' }}><div style={{ display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr',gap:40,marginBottom:48 }}><div><Logo /><p style={{ fontSize:13,color:'var(--muted)',lineHeight:1.7,marginTop:14 }}>AI-powered sitemap analysis. Find your sitemap, fix your SEO.</p></div><div><div style={{ fontSize:11,fontWeight:700,color:'var(--muted-2)',textTransform:'uppercase',marginBottom:14 }}>Tools</div>{[['Sitemap Finder','/sitemap-finder'],['Sitemap Checker','/sitemap-checker'],['SEO Checker','/website-seo-checker'],['Free SEO Audit','/free-seo-audit'],['XML Generator','/xml-sitemap-generator']].map(([l,h])=>(<a key={h} href={h} style={{ display:'block',fontSize:13,color:'var(--muted)',textDecoration:'none',marginBottom:10 }}>{l}</a>))}</div><div><div style={{ fontSize:11,fontWeight:700,color:'var(--muted-2)',textTransform:'uppercase',marginBottom:14 }}>Learn</div>{[['What is an XML Sitemap','/learn/what-is-an-xml-sitemap'],['Sitemap Best Practices','/learn/sitemap-best-practices'],['Why Pages Not Indexed','/learn/why-pages-not-indexed'],['How to Create a Sitemap','/learn/how-to-create-a-sitemap']].map(([l,h])=>(<a key={h} href={h} style={{ display:'block',fontSize:13,color:'var(--muted)',textDecoration:'none',marginBottom:10 }}>{l}</a>))}</div><div><div style={{ fontSize:11,fontWeight:700,color:'var(--muted-2)',textTransform:'uppercase',marginBottom:14 }}>Errors</div>{[['Duplicate URLs','/sitemap-errors/duplicate-urls'],['Invalid URLs','/sitemap-errors/invalid-urls'],['Too Many URLs','/sitemap-errors/too-many-urls'],['Incorrect Priority','/sitemap-errors/incorrect-priority']].map(([l,h])=>(<a key={h} href={h} style={{ display:'block',fontSize:13,color:'var(--muted)',textDecoration:'none',marginBottom:10 }}>{l}</a>))}</div></div><div style={{ borderTop:'1px solid var(--border)',paddingTop:24,display:'flex',justifyContent:'space-between' }}><p style={{ fontSize:12,color:'var(--muted-2)' }}>2025 SitemapFixer</p><a href="/sitemap.xml" style={{ fontSize:12,color:'var(--muted-2)',textDecoration:'none' }}>Sitemap</a></div></div></footer>); }

function Features() { const items = [{ icon:'🔍',title:'Instant Sitemap Discovery',desc:'Find your sitemap across 20+ common paths in seconds.' },{ icon:'🤖',title:'AI-Powered Analysis',desc:'Claude AI generates specific recommendations for your site.' },{ icon:'📊',title:'Prioritized Fix List',desc:'Ranked list of what to fix, create, and link.' },{ icon:'⚡',title:'Under 60 Seconds',desc:'Full AI report, free, no signup.' },{ icon:'🗺️',title:'All Sitemap Formats',desc:'WordPress, Shopify, Next.js - all work.' },{ icon:'🎯',title:'Site-Specific Insights',desc:'Based on your actual URL patterns.' }]; return (<section style={{ maxWidth:960,margin:'0 auto',padding:'80px 24px' }}><div style={{ textAlign:'center',marginBottom:56 }}><h2 style={{ fontFamily:"'Instrument Serif',serif",fontSize:36,color:'var(--ink)',marginBottom:14 }}>Why SitemapFixer?</h2><p style={{ fontSize:16,color:'var(--muted)',maxWidth:480,margin:'0 auto' }}>Most SEO tools give scores. We give a specific action plan.</p></div><div style={{ display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:24 }}>{items.map(item=>(<div key={item.title} style={{ background:'white',border:'1px solid var(--border)',borderRadius:14,padding:'28px 24px' }}><div style={{ fontSize:28,marginBottom:14 }}>{item.icon}</div><div style={{ fontSize:15,fontWeight:700,color:'var(--ink)',marginBottom:8 }}>{item.title}</div><div style={{ fontSize:13,color:'var(--muted)',lineHeight:1.65 }}>{item.desc}</div></div>))}</div></section>); }

function HowItWorks() { const steps = [{ num:'1',title:'Enter your domain',desc:'Type any domain. No sitemap URL needed.' },{ num:'2',title:'We find your sitemap',desc:'We locate it, fetch every URL, and cluster them.' },{ num:'3',title:'AI generates your plan',desc:'Claude produces specific, ranked recommendations.' },{ num:'4',title:'Fix and grow',desc:'Create missing pages, fix patterns, build links.' }]; return (<section style={{ background:'white',borderTop:'1px solid var(--border)',borderBottom:'1px solid var(--border)' }}><div style={{ maxWidth:960,margin:'0 auto',padding:'80px 24px' }}><h2 style={{ fontFamily:"'Instrument Serif',serif",fontSize:36,color:'var(--ink)',marginBottom:56,textAlign:'center' }}>How it works</h2><div style={{ display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:32 }}>{steps.map(s=>(<div key={s.num} style={{ textAlign:'center' }}><div style={{ width:44,height:44,borderRadius:'50%',background:'var(--ink)',color:'white',fontSize:18,fontWeight:700,display:'flex',alignItems:'center',justifyContent:'center',margin:'0 auto 18px' }}>{s.num}</div><div style={{ fontSize:15,fontWeight:700,color:'var(--ink)',marginBottom:8 }}>{s.title}</div><div style={{ fontSize:13,color:'var(--muted)',lineHeight:1.65 }}>{s.desc}</div></div>))}</div></div></section>); }

function Testimonials() {
  const reviews = [
      { name:'Marcus Chen', role:'Head of SEO', company:'Growthly', av:{ bg:'#e0e7ff',c:'#4338ca',l:'M' }, text:"I had 47 pages Google refused to index for 3 months. SitemapFixer found a misconfigured noindex tag from a staging migration in 30 seconds. Fixed it the same day -- all 47 pages indexed within a week." },
          { name:'Sarah Okafor', role:'Founder', company:'ContentStack.io', av:{ bg:'#fce7f3',c:'#9d174d',l:'S' }, text:"Our organic traffic was flat for 6 months despite publishing constantly. 200+ duplicate URLs eating crawl budget. SitemapFixer diagnosed it immediately. Traffic up 40% in 8 weeks." },
              { name:'James Whitfield', role:'Technical SEO Lead', company:'Shopwave', av:{ bg:'#dcfce7',c:'#166534',l:'J' }, text:"I've used Screaming Frog, Ahrefs, Semrush -- none gave me the sitemap analysis SitemapFixer did in under a minute. Recommendations were specific to our Next.js setup. Actually useful." },
                  { name:'Anika Patel', role:'SEO Consultant', company:'Independent', av:{ bg:'#fef3c7',c:'#92400e',l:'A' }, text:"I use this for every client onboarding now. Screenshot the report and instantly know the 3 highest-impact things to fix. Saves me 2 hours of manual audit per client." },
                      { name:'Ryan Torres', role:'CTO', company:'Launchpad SaaS', av:{ bg:'#e0f2fe',c:'#075985',l:'R' }, text:"We launched and had zero search traffic after 4 months. SitemapFixer found our sitemap was returning 404 -- our deployment pipeline had broken the route. Fixed in 20 minutes." },
                          { name:'Lena Hoffmann', role:'Growth Manager', company:'Fintools GmbH', av:{ bg:'#f3e8ff',c:'#7c3aed',l:'L' }, text:"It doesn't just say 'fix your sitemap' -- it tells me exactly which URL patterns are missing, why, and what to add. That's consultant-level advice for free." },
                            ];
                              return (
                                  <section style={{ background:'white',borderTop:'1px solid var(--border)',borderBottom:'1px solid var(--border)',padding:'80px 24px' }}>
                                        <div style={{ maxWidth:960,margin:'0 auto' }}>
                                                <div style={{ textAlign:'center',marginBottom:56 }}>
                                                          <h2 style={{ fontFamily:"'Instrument Serif',serif",fontSize:36,color:'var(--ink)',marginBottom:14 }}>What SEOs actually say</h2>
                                                                    <p style={{ fontSize:16,color:'var(--muted)',maxWidth:480,margin:'0 auto' }}>Real results from real SEOs -- no PR quotes, no paid testimonials.</p>
                                                                            </div>
                                                                                    <div style={{ display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20 }}>
                                                                                              {reviews.map(r=>(
                                                                                                          <div key={r.name} style={{ background:'var(--paper)',border:'1px solid var(--border)',borderRadius:16,padding:'24px',display:'flex',flexDirection:'column',gap:16 }}>
                                                                                                                        <div style={{ display:'flex',gap:2 }}>{[1,2,3,4,5].map(s=><span key={s} style={{ color:'#f59e0b',fontSize:14 }}>&#9733;</span>)}</div>
                                                                                                                                      <p style={{ fontSize:14,color:'var(--ink)',lineHeight:1.7,flex:1,margin:0 }}>&ldquo;{r.text}&rdquo;</p>
                                                                                                                                                    <div style={{ display:'flex',alignItems:'center',gap:10 }}>
                                                                                                                                                                    <div style={{ width:36,height:36,borderRadius:'50%',background:r.av.bg,display:'flex',alignItems:'center',justifyContent:'center',fontSize:14,fontWeight:700,color:r.av.c,flexShrink:0 }}>{r.av.l}</div>
                                                                                                                                                                                    <div><div style={{ fontSize:13,fontWeight:700,color:'var(--ink)' }}>{r.name}</div><div style={{ fontSize:12,color:'var(--muted)' }}>{r.role} &middot; {r.company}</div></div>
                                                                                                                                                                                                  </div>
                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                          </section>
                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                            function EmailCapture() {
                                                                                                                                                                                                                                              return (
                                                                                                                                                                                                                                                  <section style={{ background:'linear-gradient(135deg,#0a0a0f 0%,#1a1a2e 100%)',padding:'80px 24px' }}>
                                                                                                                                                                                                                                                        <div style={{ maxWidth:640,margin:'0 auto',textAlign:'center' }}>
                                                                                                                                                                                                                                                                <div style={{ display:'inline-flex',alignItems:'center',gap:6,background:'rgba(45,91,227,0.2)',border:'1px solid rgba(45,91,227,0.4)',borderRadius:99,padding:'5px 14px',fontSize:12,fontWeight:600,color:'#93c5fd',letterSpacing:'0.04em',textTransform:'uppercase',marginBottom:24 }}>
                                                                                                                                                                                                                                                                          <span style={{ fontSize:10 }}>●</span> Free Resource
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                          <h2 style={{ fontFamily:"'Instrument Serif',serif",fontSize:36,color:'white',marginBottom:16,lineHeight:1.15 }}>Get the Sitemap Audit Checklist</h2>
                                                                                                                                                                                                                                                                                                  <p style={{ fontSize:16,color:'#9ca3af',lineHeight:1.65,marginBottom:36,maxWidth:480,margin:'0 auto 36px' }}>The exact 23-point checklist our AI uses to audit sitemaps. Find crawl budget leaks, indexing blocks, and structural gaps -- free PDF, no spam.</p>
                                                                                                                                                                                                                                                                                                          <div style={{ display:'flex',gap:10,maxWidth:480,margin:'0 auto',background:'rgba(255,255,255,0.08)',border:'1px solid rgba(255,255,255,0.15)',borderRadius:12,padding:'6px 6px 6px 18px' }}>
                                                                                                                                                                                                                                                                                                                    <input type="email" placeholder="your@email.com" style={{ flex:1,background:'transparent',border:'none',outline:'none',fontSize:15,color:'white',fontFamily:'inherit' }} />
                                                                                                                                                                                                                                                                                                                              <button style={{ background:'#2d5be3',color:'white',border:'none',borderRadius:8,padding:'10px 20px',fontSize:14,fontWeight:600,cursor:'pointer',whiteSpace:'nowrap',flexShrink:0 }}>Send me the checklist</button>
                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                              <p style={{ fontSize:12,color:'#6b7280',marginTop:14 }}>No spam. Unsubscribe anytime. Sent instantly.</p>
                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                          function BlogSection() { const posts = [{ title:'Sitemap Not Working? 9 Common Fixes',desc:'The most common reasons sitemaps fail.',href:'/learn/sitemap-not-working',tag:'Guide' },{ title:'Pages Not Indexed by Google',desc:'Every reason and step-by-step fixes.',href:'/learn/pages-not-indexed-google',tag:'Guide' },{ title:'Submitted URL Not Indexed',desc:'What this Search Console status means.',href:'/learn/submitted-url-not-indexed',tag:'Guide' },{ title:'Crawled Currently Not Indexed',desc:'Google crawled but chose not to index.',href:'/learn/crawled-currently-not-indexed',tag:'Guide' },{ title:'Sitemap Errors in Search Console',desc:'Every error type and how to fix each one.',href:'/learn/sitemap-errors-google-search-console',tag:'Guide' },{ title:'Google Not Crawling My Site',desc:'All reasons Googlebot stops crawling.',href:'/learn/google-not-crawling-my-site',tag:'Guide' }]; return (<section style={{ maxWidth:960,margin:'0 auto',padding:'80px 24px' }}><div style={{ display:'flex',justifyContent:'space-between',alignItems:'flex-end',marginBottom:40 }}><div><h2 style={{ fontFamily:"'Instrument Serif',serif",fontSize:36,color:'var(--ink)',marginBottom:8 }}>Learn SEO</h2><p style={{ fontSize:15,color:'var(--muted)' }}>Free guides on sitemaps, crawl budget, and technical SEO.</p></div><a href="/learn" style={{ fontSize:13,color:'var(--accent)',textDecoration:'none',fontWeight:600 }}>View all</a></div><div style={{ display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:20 }}>{posts.map(p=>(<a key={p.href} href={p.href} style={{ display:'block',textDecoration:'none',background:'white',border:'1px solid var(--border)',borderRadius:14,padding:'24px' }}><span style={{ display:'inline-block',fontSize:11,fontWeight:700,color:'var(--accent)',background:'var(--accent-light)',borderRadius:4,padding:'2px 8px',marginBottom:12 }}>{p.tag}</span><div style={{ fontSize:15,fontWeight:700,color:'var(--ink)',marginBottom:8 }}>{p.title}</div><div style={{ fontSize:13,color:'var(--muted)',lineHeight:1.6 }}>{p.desc}</div></a>))}</div></section>); }

                                                                                                                                                                                                                                                                                                                                                          export default function Home() {
                                                                                                                                                                                                                                                                                                                                                              const [state, setState] = useState<AppState>('idle');
                                                                                                                                                                                                                                                                                                                                                                const [domain, setDomain] = useState('');
                                                                                                                                                                                                                                                                                                                                                                  const [results, setResults] = useState<null | object>(null);
                                                                                                                                                                                                                                                                                                                                                                    const [error, setError] = useState<string | null>(null);
                                                                                                                                                                                                                                                                                                                                                                      const [showPaywall, setShowPaywall] = useState(false);
                                                                                                                                                                                                                                                                                                                                                                        const [paywallDomain, setPaywallDomain] = useState('');

                                                                                                                                                                                                                                                                                                                                                                          async function handleAnalyze(inputDomain: string) {
                                                                                                                                                                                                                                                                                                                                                                                const count = parseInt(typeof window !== 'undefined' ? (localStorage.getItem('sf_count') || '0') : '0');
                                                                                                                                                                                                                                                                                                                                                                                    if (count >= 1) { setPaywallDomain(inputDomain); setShowPaywall(true); return; }
                                                                                                                                                                                                                                                                                                                                                                                        setDomain(inputDomain); setState('loading'); setError(null); setResults(null);
                                                                                                                                                                                                                                                                                                                                                                                            try {
                                                                                                                                                                                                                                                                                                                                                                                                    const res = await fetch('/api/analyze', { method:'POST', headers:{ 'Content-Type':'application/json' }, body:JSON.stringify({ domain:inputDomain }) });
                                                                                                                                                                                                                                                                                                                                                                                                          const data = await res.json();
                                                                                                                                                                                                                                                                                                                                                                                                                if (!res.ok) { setError(data.error === 'no_sitemap' ? data.message : (data.error || 'Something went wrong.')); setState('error'); return; }
                                                                                                                                                                                                                                                                                                                                                                                                                      setResults(data); setState('results');
                                                                                                                                                                                                                                                                                                                                                                                                                            if (typeof window !== 'undefined') localStorage.setItem('sf_count', String(count + 1));
                                                                                                                                                                                                                                                                                                                                                                                            } catch { setError('Network error.'); setState('error'); }
                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                function reset() { setState('idle'); setResults(null); setError(null); }

                                                                                                                                                                                                                                                                                                                                                                                                  return (
                                                                                                                                                                                                                                                                                                                                                                                                        <div style={{ minHeight:'100vh',background:'var(--paper)' }}>
                                                                                                                                                                                                                                                                                                                                                                                                                <Navbar />
                                                                                                                                                                                                                                                                                                                                                                                                                      <main>
                                                                                                                                                                                                                                                                                                                                                                                                                                {state === 'idle' && (<><Hero onSubmit={handleAnalyze} loading={false} variant="default" /><Features /><HowItWorks /><Testimonials /><EmailCapture /><BlogSection /></>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                        {state === 'loading' && <Loading domain={domain} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                {state === 'error' && (<div style={{ maxWidth:540,margin:'80px auto',padding:'0 24px',textAlign:'center' }}><div style={{ fontSize:40,marginBottom:20 }}>🔍</div><h2 style={{ fontSize:24,fontWeight:700,color:'var(--ink)',marginBottom:12 }}>Sitemap not found</h2><p style={{ fontSize:15,color:'var(--muted)',lineHeight:1.6,marginBottom:32 }}>{error}</p><button onClick={reset} className="cta-btn">Try another domain</button></div>)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                        {state === 'results' && results && (<Results data={results as any} onReset={reset} />)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {state === 'idle' && <Footer />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {showPaywall && <PaywallModal domain={paywallDomain} onClose={() => setShowPaywall(false)} />}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                  }