import type { Metadata } from 'next';
export const metadata: Metadata = { title: 'Google Search Console Sitemap: Submit, Monitor, and Fix | SitemapFixer', description: 'Learn how to submit your sitemap in Google Search Console, monitor indexing status, and fix common sitemap errors that prevent pages from being indexed.', alternates: { canonical: 'https://sitemapfixer.com/learn/google-search-console-sitemap' }, openGraph: { title: 'Google Search Console Sitemap: Submit and Fix Issues', description: 'Learn how to submit your sitemap in Google Search Console, monitor indexing status, and fix common sitemap errors that prevent pages from being indexed.', url: 'https://sitemapfixer.com/learn/google-search-console-sitemap', type: 'article' } };
export default function Page() { return (
  <div style={{ maxWidth: 800, margin: '0 auto', padding: '60px 24px' }}>
    <nav style={{ fontSize: 13, color: '#6b6b7d', marginBottom: 32 }}><a href="/" style={{ color: '#2d5be3', textDecoration: 'none' }}>Home</a>{' / '}<a href="/learn" style={{ color: '#2d5be3', textDecoration: 'none' }}>Learn</a>{' / '}<span>Google Search Console Sitemap: Submit and Fix Issues</span></nav>
    <h1 style={{ fontSize: 40, fontWeight: 700, color: '#0a0a0f', marginBottom: 16, lineHeight: 1.15 }}>Google Search Console Sitemap: Submit and Fix Issues</h1>
    <div style={{ background: '#eef1ff', border: '1px solid rgba(45,91,227,0.2)', borderRadius: 12, padding: '16px 20px', marginBottom: 40, display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16 }}><span style={{ fontSize: 14, color: '#2d5be3', fontWeight: 500 }}>Check your sitemap free</span><a href="/" style={{ background: '#2d5be3', color: 'white', padding: '10px 20px', borderRadius: 8, textDecoration: 'none', fontWeight: 600, fontSize: 13 }}>Analyze Free</a></div>
    <div style={{ fontSize: 16, color: '#3d3d4f', lineHeight: 1.8 }}>
        <h2 style={{ fontSize: 24, fontWeight: 700, color: '#0a0a0f', marginTop: 40, marginBottom: 12 }}>How to Submit Your Sitemap</h2>
        <p style={{ marginBottom: 20 }}>Log into Google Search Console and select your property. In the left sidebar click Sitemaps. Enter your sitemap URL such as yourdomain.com/sitemap.xml and click Submit. Google will begin processing within 24-48 hours.</p>
        <h2 style={{ fontSize: 24, fontWeight: 700, color: '#0a0a0f', marginTop: 40, marginBottom: 12 }}>Reading the Sitemap Report</h2>
        <p style={{ marginBottom: 20 }}>After submission the Sitemaps report shows: submission date, last time Google read your sitemap, number of URLs discovered, and number of URLs indexed. A large gap between discovered and indexed is a warning sign worth investigating.</p>
        <h2 style={{ fontSize: 24, fontWeight: 700, color: '#0a0a0f', marginTop: 40, marginBottom: 12 }}>Common Sitemap Errors in Search Console</h2>
        <p style={{ marginBottom: 20 }}>Common errors include: Could Not Fetch meaning server issue, Sitemap is an HTML page meaning wrong URL, Unsupported file format meaning not valid XML, and HTTP errors like 403, 404, or 500.</p>
        <h2 style={{ fontSize: 24, fontWeight: 700, color: '#0a0a0f', marginTop: 40, marginBottom: 12 }}>Why Indexed Count Is Lower Than Submitted</h2>
        <p style={{ marginBottom: 20 }}>It is normal for indexed count to be lower than submitted. Google applies quality filters and skips thin content, duplicate pages, noindex pages, and pages blocked by robots.txt. Focus on improving content quality for non-indexed pages.</p>
        <h2 style={{ fontSize: 24, fontWeight: 700, color: '#0a0a0f', marginTop: 40, marginBottom: 12 }}>Using URL Inspection Tool</h2>
        <p style={{ marginBottom: 20 }}>For individual pages with indexing problems, use the URL Inspection tool. Paste the URL and Google shows its exact crawl status, last crawl date, canonical URL, page rendering, and any specific indexing issues.</p>
        <h2 style={{ fontSize: 24, fontWeight: 700, color: '#0a0a0f', marginTop: 40, marginBottom: 12 }}>Monitoring Sitemap Health Over Time</h2>
        <p style={{ marginBottom: 20 }}>Check your sitemap report weekly, especially after site changes. Sudden drops in indexed pages, new errors, or a spike in discovered-but-not-indexed pages are early warning signs of technical SEO problems.</p>
    </div>
    <div style={{ background: '#0a0a0f', borderRadius: 12, padding: '32px', textAlign: 'center', marginTop: 48 }}><div style={{ fontSize: 20, fontWeight: 700, color: 'white', marginBottom: 8 }}>Analyze your sitemap now</div><div style={{ color: '#9999aa', marginBottom: 20, fontSize: 14 }}>Free analysis in 60 seconds</div><a href="/" style={{ background: 'white', color: '#0a0a0f', padding: '14px 28px', borderRadius: 8, textDecoration: 'none', fontWeight: 700 }}>Analyze My Sitemap</a></div>
    <div style={{ marginTop: 48, borderTop: '1px solid #e4e4ed', paddingTop: 32 }}><div style={{ fontWeight: 600, color: '#0a0a0f', marginBottom: 16 }}>Related guides</div><ul style={{ listStyle: 'none', padding: 0, display: 'flex', gap: 12, flexWrap: 'wrap' }}>
          <li><a href="/learn/sitemap-errors-google-search-console" style={{ color: '#2d5be3', textDecoration: 'none', background: '#eef1ff', padding: '6px 14px', borderRadius: 6, fontSize: 13 }}>Sitemap Errors in Search Console</a></li>
          <li><a href="/learn/submitted-url-not-indexed" style={{ color: '#2d5be3', textDecoration: 'none', background: '#eef1ff', padding: '6px 14px', borderRadius: 6, fontSize: 13 }}>Submitted URL Not Indexed</a></li>
          <li><a href="/learn/sitemap-not-working" style={{ color: '#2d5be3', textDecoration: 'none', background: '#eef1ff', padding: '6px 14px', borderRadius: 6, fontSize: 13 }}>Sitemap Not Working</a></li>
    </ul></div>
  </div>); }
