'use client';
import { useState } from 'react';

interface HeroProps { onSubmit: (domain: string) => void; loading: boolean; variant?: 'default' | 'sitemap-finder' | 'sitemap-checker' | 'website-seo-checker' | 'xml-sitemap-generator' | 'free-seo-audit'; }

const COPY = {
  default: { eyebrow: 'Free Sitemap Checker & Indexing Fix', headline: 'Fix Crawled – Currently\nNot Indexed. Free.', sub: 'Pages crawled but not indexed by Google? Our AI sitemap checker finds exactly why — and gives you a prioritized fix list in 60 seconds. Verify your sitemap, find all pages on your website, and fix indexing issues.', cta: 'Analyze My Site Free', placeholder: 'yourdomain.com' },
    'sitemap-finder': { eyebrow: 'Sitemap Finder', headline: 'Find your sitemap.\nSee all pages.', sub: 'Find the sitemap of any website instantly. See all pages on a website, list all subpages, check /sitemap.xml, robots.txt, and 20+ common paths. Free sitemap finder with AI-powered SEO recommendations.', cta: 'Find Sitemap', placeholder: 'yourdomain.com' },
      'sitemap-checker': { eyebrow: 'XML Sitemap Checker', headline: 'Check your sitemap.\nFind every error.', sub: 'Free XML sitemap checker and validator. Verify your sitemap for broken URLs, crawled but not indexed pages, and missed SEO opportunities. The easiest way to check and validate your sitemap.', cta: 'Check Sitemap', placeholder: 'yourdomain.com' },
        'xml-sitemap-generator': { eyebrow: 'XML Sitemap Generator', headline: 'Analyze your sitemap.\nGet exact fixes.', sub: 'Enter your domain — we find your XML sitemap, parse every URL, check for crawled currently not indexed issues, and generate an AI-powered action plan.', cta: 'Analyze Sitemap', placeholder: 'yourdomain.com' },
          'free-seo-audit': { eyebrow: 'Free SEO Audit', headline: 'Your free SEO audit\nin 60 seconds.', sub: 'No forms. No email required. Find crawled but not indexed pages, sitemap errors, and webpage indexing issues. Get a prioritized fix list based on your actual site structure.', cta: 'Run Free Audit', placeholder: 'yourdomain.com' },
            'website-seo-checker': { eyebrow: 'Website SEO Checker', headline: 'Your site has SEO\ngaps. Find them.', sub: 'Stop guessing what is wrong with your SEO. Find crawled currently not indexed pages, verify your sitemap, and get a prioritized action plan from our AI.', cta: 'Check SEO', placeholder: 'yourdomain.com' },
            };

            const EXAMPLES = ['stripe.com', 'linear.app', 'vercel.com', 'notion.so'];

            const AVATARS = [
              { bg: '#e0e7ff', letter: 'M', color: '#4338ca' },
                { bg: '#fce7f3', letter: 'S', color: '#9d174d' },
                  { bg: '#dcfce7', letter: 'J', color: '#166534' },
                    { bg: '#fef3c7', letter: 'A', color: '#92400e' },
                      { bg: '#e0f2fe', letter: 'R', color: '#075985' },
                      ];

                      export function Hero({ onSubmit, loading, variant = 'default' }: HeroProps) {
                        const [domain, setDomain] = useState('');
                          const copy = COPY[variant];
                            const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); if (domain.trim()) onSubmit(domain.trim()); };
                              return (
                                  <div style={{ maxWidth: 720, margin: '0 auto', padding: '80px 24px 60px', textAlign: 'center' }}>
                                        <div className="anim-fade-up" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, background: 'var(--accent-light)', border: '1px solid rgba(45,91,227,0.2)', borderRadius: 99, padding: '5px 14px', fontSize: 12, fontWeight: 600, color: 'var(--accent)', letterSpacing: '0.04em', textTransform: 'uppercase', marginBottom: 28 }}>
                                                <span style={{ fontSize: 10 }}>*</span> {copy.eyebrow}
                                                      </div>
                                                            <h1 className="anim-fade-up anim-fade-up-1 font-serif" style={{ fontSize: 'clamp(44px, 7vw, 72px)', fontWeight: 400, lineHeight: 1.08, color: 'var(--ink)', marginBottom: 20, whiteSpace: 'pre-line', letterSpacing: '-0.02em' }}>
                                                                    {copy.headline}
                                                                          </h1>
                                                                                <p className="anim-fade-up anim-fade-up-2" style={{ fontSize: 17, color: 'var(--muted)', lineHeight: 1.65, marginBottom: 44, maxWidth: 560, margin: '0 auto 44px' }}>
                                                                                        {copy.sub}
                                                                                              </p>
                                                                                                    <form onSubmit={handleSubmit} className="anim-fade-up anim-fade-up-3" style={{ display: 'flex', gap: 10, background: 'white', border: '1.5px solid var(--border)', borderRadius: 14, padding: '6px 6px 6px 18px', boxShadow: '0 2px 16px rgba(0,0,0,0.06)', maxWidth: 580, margin: '0 auto', transition: 'border-color 0.2s, box-shadow 0.2s' }} onFocus={e => { (e.currentTarget as HTMLFormElement).style.borderColor = 'var(--accent)'; (e.currentTarget as HTMLFormElement).style.boxShadow = '0 2px 20px var(--accent-glow)'; }} onBlur={e => { if (!e.currentTarget.contains(e.relatedTarget)) { (e.currentTarget as HTMLFormElement).style.borderColor = 'var(--border)'; (e.currentTarget as HTMLFormElement).style.boxShadow = '0 2px 16px rgba(0,0,0,0.06)'; } }}>
                                                                                                            <input type="text" value={domain} onChange={e => setDomain(e.target.value)} placeholder={copy.placeholder} disabled={loading} style={{ flex: 1, border: 'none', outline: 'none', fontSize: 16, color: 'var(--ink)', background: 'transparent', fontFamily: "'DM Mono', monospace", letterSpacing: '-0.01em' }} aria-label="Enter your domain" />
                                                                                                                    <button type="submit" disabled={loading || !domain.trim()} className="cta-btn" style={{ flexShrink: 0 }}>
                                                                                                                              {loading ? (<span style={{ display: 'flex', gap: 4, alignItems: 'center' }}><span className="loading-dot" /><span className="loading-dot" /><span className="loading-dot" /></span>) : copy.cta}
                                                                                                                                      </button>
                                                                                                                                            </form>
                                                                                                                                                  <div className="anim-fade-up anim-fade-up-4" style={{ display: 'flex', gap: 8, justifyContent: 'center', marginTop: 20, flexWrap: 'wrap', alignItems: 'center' }}>
                                                                                                                                                          <span style={{ fontSize: 12, color: 'var(--muted-2)' }}>Try:</span>
                                                                                                                                                                  {EXAMPLES.map(eg => (<button key={eg} onClick={() => setDomain(eg)} style={{ background: 'none', border: '1px solid var(--border)', borderRadius: 6, padding: '3px 10px', fontSize: 12, fontFamily: "'DM Mono', monospace", color: 'var(--muted)', cursor: 'pointer', transition: 'all 0.15s' }} onMouseEnter={e => { (e.target as HTMLButtonElement).style.borderColor = 'var(--accent)'; (e.target as HTMLButtonElement).style.color = 'var(--accent)'; }} onMouseLeave={e => { (e.target as HTMLButtonElement).style.borderColor = 'var(--border)'; (e.target as HTMLButtonElement).style.color = 'var(--muted)'; }}>{eg}</button>))}
                                                                                                                                                                        </div>
                                                                                                                                                                              <div className="anim-fade-up anim-fade-up-5" style={{ marginTop: 40, display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 10 }}>
                                                                                                                                                                                      <div style={{ display: 'flex', alignItems: 'center', gap: 0 }}>
                                                                                                                                                                                                {AVATARS.map((a, i) => (
                                                                                                                                                                                                            <div key={i} style={{ width: 32, height: 32, borderRadius: '50%', background: a.bg, border: '2px solid white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 13, fontWeight: 700, color: a.color, marginLeft: i === 0 ? 0 : -8, zIndex: AVATARS.length - i }}>
                                                                                                                                                                                                                          {a.letter}
                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                          <div style={{ marginLeft: 12, textAlign: 'left' }}>
                                                                                                                                                                                                                                                                      <div style={{ display: 'flex', gap: 2 }}>
                                                                                                                                                                                                                                                                                    {[1,2,3,4,5].map(s => <span key={s} style={{ color: '#f59e0b', fontSize: 14 }}>&#9733;</span>)}
                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                            <div style={{ fontSize: 12, color: 'var(--muted)', marginTop: 2 }}>Trusted by SEOs and founders</div>
                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                          }