import React from 'react';

const breadcrumbSchema = { '@context':'https://schema.org', '@type':'BreadcrumbList', itemListElement:[{ '@type':'ListItem', position:1, name:'Home', item:'https://sitemapfixer.com' },{ '@type':'ListItem', position:2, name:'Blog', item:'https://sitemapfixer.com/blog' }] };

function BlogNav() {
  return (
      <nav style={{ borderBottom:'1px solid #e4e4ed', background:'rgba(250,250,249,0.95)', backdropFilter:'blur(12px)', position:'sticky', top:0, zIndex:100 }}>
            <div style={{ maxWidth:860, margin:'0 auto', padding:'14px 24px', display:'flex', alignItems:'center', justifyContent:'space-between' }}>
                    <a href="/" style={{ display:'flex', alignItems:'center', gap:8, textDecoration:'none' }}>
                              <svg width="28" height="28" viewBox="0 0 28 28" fill="none"><rect width="28" height="28" rx="7" fill="#0a0a0f"/><path d="M7 9h14M7 14h10M7 19h12" stroke="white" strokeWidth="2" strokeLinecap="round"/><circle cx="21" cy="19" r="3" fill="#2d5be3"/></svg>
                                        <span style={{ fontFamily:"'Instrument Serif',serif", fontSize:20, color:'#0a0a0f' }}>SitemapFixer</span>
                                                </a>
                                                        <div style={{ display:'flex', gap:24, alignItems:'center' }}>
                                                                  <a href="/learn" style={{ fontSize:14, color:'#3d3d4f', textDecoration:'none' }}>Learn</a>
                                                                            <a href="/blog" style={{ fontSize:14, color:'#2d5be3', fontWeight:600, textDecoration:'none' }}>Blog</a>
                                                                                      <a href="/pricing" style={{ fontSize:14, color:'#3d3d4f', textDecoration:'none' }}>Pricing</a>
                                                                                                <a href="/" style={{ background:'#2d5be3', color:'white', padding:'8px 18px', borderRadius:8, fontSize:14, fontWeight:600, textDecoration:'none' }}>Free Audit</a>
                                                                                                        </div>
                                                                                                              </div>
                                                                                                                  </nav>
                                                                                                                    );
                                                                                                                    }

                                                                                                                    function BlogCTABar() {
                                                                                                                      return (
                                                                                                                          <div style={{ position:'sticky', bottom:0, zIndex:99, background:'#0a0a0f', borderTop:'1px solid rgba(255,255,255,0.1)', padding:'14px 24px' }}>
                                                                                                                                <div style={{ maxWidth:860, margin:'0 auto', display:'flex', alignItems:'center', justifyContent:'space-between', gap:16, flexWrap:'wrap' }}>
                                                                                                                                        <div style={{ display:'flex', alignItems:'center', gap:12 }}>
                                                                                                                                                  <div style={{ width:8, height:8, borderRadius:'50%', background:'#22c55e', flexShrink:0 }} />
                                                                                                                                                            <span style={{ fontSize:14, color:'#e5e7eb', fontWeight:500 }}>Is your sitemap hurting your Google rankings?</span>
                                                                                                                                                                    </div>
                                                                                                                                                                            <a href="/" style={{ background:'#2d5be3', color:'white', padding:'9px 20px', borderRadius:8, fontSize:14, fontWeight:600, textDecoration:'none', whiteSpace:'nowrap', flexShrink:0 }}>
                                                                                                                                                                                      Check for free &rarr;
                                                                                                                                                                                              </a>
                                                                                                                                                                                                    </div>
                                                                                                                                                                                                        </div>
                                                                                                                                                                                                          );
                                                                                                                                                                                                          }

                                                                                                                                                                                                          function BlogFooter() {
                                                                                                                                                                                                            return (
                                                                                                                                                                                                                <footer style={{ borderTop:'1px solid #e4e4ed', background:'#fafaf9', padding:'40px 24px 24px' }}>
                                                                                                                                                                                                                      <div style={{ maxWidth:860, margin:'0 auto', display:'flex', justifyContent:'space-between', alignItems:'center', flexWrap:'wrap', gap:16 }}>
                                                                                                                                                                                                                              <div style={{ display:'flex', alignItems:'center', gap:8 }}>
                                                                                                                                                                                                                                        <svg width="20" height="20" viewBox="0 0 28 28" fill="none"><rect width="28" height="28" rx="7" fill="#0a0a0f"/><path d="M7 9h14M7 14h10M7 19h12" stroke="white" strokeWidth="2" strokeLinecap="round"/><circle cx="21" cy="19" r="3" fill="#2d5be3"/></svg>
                                                                                                                                                                                                                                                  <span style={{ fontWeight:600, fontSize:14, color:'#0a0a0f' }}>SitemapFixer</span>
                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                  <div style={{ display:'flex', gap:24 }}>
                                                                                                                                                                                                                                                                            {([['Blog','/blog'],['Learn','/learn'],['Terms','/terms'],['Privacy','/privacy'],['Sitemap','/sitemap.xml']] as [string,string][]).map(([t,h])=>(
                                                                                                                                                                                                                                                                                        <a key={h} href={h} style={{ fontSize:13, color:'#6b6b7d', textDecoration:'none' }}>{t}</a>
                                                                                                                                                                                                                                                                                                  ))}
                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                  <span style={{ fontSize:12, color:'#9ca3af' }}>&copy; 2025 SitemapFixer</span>
                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                            </footer>
                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                              export default function BlogLayout({ children }: { children: React.ReactNode }) {
                                                                                                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                                                                                                    <>
                                                                                                                                                                                                                                                                                                                                          <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
                                                                                                                                                                                                                                                                                                                                                <BlogNav />
                                                                                                                                                                                                                                                                                                                                                      <main>{children}</main>
                                                                                                                                                                                                                                                                                                                                                            <BlogFooter />
                                                                                                                                                                                                                                                                                                                                                                  <BlogCTABar />
                                                                                                                                                                                                                                                                                                                                                                      </>
                                                                                                                                                                                                                                                                                                                                                                        );
                                                                                                                                                                                                                                                                                                                                                                        }→©